apiVersion: wac-fiit.github.io/v1alpha1
kind: Project
metadata:
  name: xle-ambulance-wl # napr. <pfx>-ambulance-wl
spec:
  title: "Zoznam čakajúcich xle" # napr. "Zoznam čakajúcich <pfx>"
  description: <project description> # napr. "Spravuje zoznam pacientov čakajúcich na vyšetrenie v ambulancii"
  authors: "Lukas lechman" # Zadajte mená autorov
  azureLink: "https://<sub-domain>.azurewebsites.net"
  frontendRepoUrl: "https://github.com/lukaslechman/ambulance-ufe"
  backendRepoUrl: "https://github.com/lukaslechman/ambulance-webapi
  gitopsRepoUrl: "https://github.com/lukaslechman/wac-gitops"