apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: xle-ambulance-ufe-content
spec:
  microFrontend: xle-ambulance-ufe
  element: xle-ambulance-wl-app
  attributes:
    - name: api-base
      value: http://localhost:30081/api

    - name: ambulance-id
      value: bobulova
    - name: base-path
      value: ./xle-ambulance-wl/
  displayRules:
    - allOf:
      - context-name: main-content
      - path: "^(\\.?/)?xle-ambulance-wl(/.*)?$"