apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: xle-ambulance-ufe-content
spec:
  microFrontend: xle-ambulance-ufe
  element: xle-ambulance-wl-list
  displayRules:
    - allOf:
      - context-name: main-content
      - path: "^(\\.?/)?xle-ambulance-wl(/.*)?$"